=== helgoboss/reaboot/core/bindings/recipe.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Recipe",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "description": {
      "type": [
        "string",
        "null"
      ]
    },
    "features": {
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": {
        "$ref": "#/definitions/Feature"
      }
    },
    "name": {
      "type": "string"
    },
    "required_packages": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "skip_additional_packages": {
      "type": [
        "boolean",
        "null"
      ]
    },
    "sub_title": {
      "type": [
        "string",
        "null"
      ]
    },
    "website": {
      "type": [
        "string",
        "null"
      ]
    }
  },
  "definitions": {
    "Feature": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "default": {
          "type": [
            "boolean",
            "null"
          ]
        },
        "description": {
          "type": [
            "string",
            "null"
          ]
        },
        "name": {
          "type": "string"
        },
        "packages": {
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== helgoboss/reaboot/recipes/default.json
{
  "name": "ReaBoot Classics",
  "sub_title": "all-time popular REAPER extensions",
  "description": "This recipe allows you to easily install some of the most popular REAPER extensions out there. Everything is optional, so you can choose yourself what to install and what not.",
  "website": "https://www.reaboot.com/",
  "required_packages": [],
  "features": {
    "sws": {
      "name": "SWS/S&M Extension",
      "description": "Popular and established extension that adds a variety of smaller features to REAPER. Considered as must-have by many.",
      "packages": [
        "https://raw.githubusercontent.com/ReaTeam/Extensions/master/index.xml#p=Extensions/reaper-oss_SWS.ext&v=latest"
      ]
    },
    "helgobox": {
      "name": "Helgobox (ReaLearn & Playtime)",
      "description": "Suite that provides ReaLearn (a versatile controller integration tool) and Playtime (a modern session view / clip launcher)",
      "packages": [
        "https://github.com/helgoboss/reaper-packages/raw/master/index.xml#p=Extensions/ReaLearn-x64&v=latest"
      ]
    }
  }
}
